[build]
  command = "ng build --configuration production"
  publish = "dist/imageToText/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = { Language = "text/html" }
